# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from hints import service_pb2 as hints_dot_service__pb2


class SqrtOracleStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Sqrt = channel.unary_unary(
                '/oracle.SqrtOracle/Sqrt',
                request_serializer=hints_dot_service__pb2.Request.SerializeToString,
                response_deserializer=hints_dot_service__pb2.Response.FromString,
                )


class SqrtOracleServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Sqrt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SqrtOracleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Sqrt': grpc.unary_unary_rpc_method_handler(
                    servicer.Sqrt,
                    request_deserializer=hints_dot_service__pb2.Request.FromString,
                    response_serializer=hints_dot_service__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'oracle.SqrtOracle', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SqrtOracle(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Sqrt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/oracle.SqrtOracle/Sqrt',
            hints_dot_service__pb2.Request.SerializeToString,
            hints_dot_service__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
