# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hints/service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13hints/service.proto\x12\x06oracle\"\x14\n\x07Request\x12\t\n\x01n\x18\x01 \x01(\x04\"\x19\n\x08Response\x12\r\n\x05value\x18\x01 \x03(\x04\x32\x37\n\nSqrtOracle\x12)\n\x04Sqrt\x12\x0f.oracle.Request\x1a\x10.oracle.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hints.service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUEST']._serialized_start=31
  _globals['_REQUEST']._serialized_end=51
  _globals['_RESPONSE']._serialized_start=53
  _globals['_RESPONSE']._serialized_end=78
  _globals['_SQRTORACLE']._serialized_start=80
  _globals['_SQRTORACLE']._serialized_end=135
# @@protoc_insertion_point(module_scope)
